config/routes.rb
Rails.application.routes.draw do


  resources :theatres

  get 'theatre/index'

  post '/rate' => 'rater#create', :as => 'rate'


  devise_for :users

  scope "/admin" do
    resources :users
  end

  root :to => 'welcome#index'

  resources :orders
  resources :items
  resources :users
  resources :roles
  resources :products, only: [:index]
  resources :theatres


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
        can :manage, :all
    elsif user.koordynator?
        can :read, Item
        can :create, Item
    elsif user.pracownik?
      can :manage, Order, ClientOrder
    elsif user.klient?
        can :read, Item
    else
        can :read, Item
    end
    
  end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/client_order.rb
class ClientOrder < ActiveRecord::Base
	def index
		@status = OrderStatus.all
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
	ratyrate_rateable "speed", "engine", "price"
	mount_uploader :photo, PhotoUploader

	validates :name, presence: true




end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal
 
  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def item_present
    if item.nil?
      errors.add(:item, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/theatre.rb
class Theatre < ActiveRecord::Base

	def self.search(search)
  		where("name LIKE ?", "%#{search}%") 

	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ratyrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  has_many :magazines

  before_save :assign_role

  def assign_role
  	self.role = Role.find_by name: "Klient" if self.role.nil?
  end

  def admin?
    self.role && self.role.name == "Admin"
  end

  def koordynator?
    self.role && self.role.name == "koordynator"
  end

  def klient?
    self.role && self.role.name == "Klient"
  end

  def pracownik?
    self.role && self.role.name == "pracownik"
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

  def checkout
    @order_items = current_order.order_items
  end
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  before_action :set_theatre, only: [:show, :edit, :update, :destroy]

  # GET /theatres
  # GET /theatres.json
  def index
    if params[:search]
      @theatres = Theatre.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 5)
    else
      @theatres = Theatre.all.order(:name).paginate(page: params[:page], per_page: 5)
    end
  end

  # GET /theatres/1
  # GET /theatres/1.json
  def show
  end

  # GET /theatres/new
  def new
    @theatre = Theatre.new
  end

  # GET /theatres/1/edit
  def edit
  end

  # POST /theatres
  # POST /theatres.json
  def create
    @theatre = Theatre.new(theatre_params)

    respond_to do |format|
      if @theatre.save
        format.html { redirect_to @theatre, notice: 'Theatre was successfully created.' }
        format.json { render :show, status: :created, location: @theatre }
      else
        format.html { render :new }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theatres/1
  # PATCH/PUT /theatres/1.json
  def update
    respond_to do |format|
      if @theatre.update(theatre_params)
        format.html { redirect_to @theatre, notice: 'Theatre was successfully updated.' }
        format.json { render :show, status: :ok, location: @theatre }
      else
        format.html { render :edit }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatres/1
  # DELETE /theatres/1.json
  def destroy
    @theatre.destroy
    respond_to do |format|
      format.html { redirect_to theatres_url, notice: 'Theatre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theatre
      @theatre = Theatre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theatre_params
      params.require(:theatre).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/theatre_helper.rb
module TheatreHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/theatres/_form.html.erb
<%= form_for(@theatre) do |f| %>
  <% if @theatre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theatre.errors.count, "error") %> prohibited this theatre from being saved:</h2>

      <ul>
      <% @theatre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theatres/_theatre.html.erb
  <tbody>
      <% @theatres.each do |theatre| %>
      <tr>
        <td><%= theatre.name %></td>
        <td><%= theatre.description %></td>
        <td><%= link_to 'Show', theatre %></td>
        <td><%= link_to 'Edit', edit_theatre_path(theatre) %></td>
        <td><%= link_to 'Destroy', theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

app/views/theatres/edit.html.erb
<h1>Editing Theatre</h1>

<%= render 'form' %>

<%= link_to 'Show', @theatre %> |
<%= link_to 'Back', theatres_path %>

app/views/theatres/index.html.erb
<%= form_tag(theatres_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search theatres" %>
<%= submit_tag "Search" %>
<% end %>


<% if (@theatres.present?) &&  (params.has_key?(:search))%>
  <%= render @theatres %>
<% elsif (params.has_key?(:search)) %>
  <p>There are no theatres containing the term(s) <%= params[:search] %>.</p>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Listing Theatres</h1>

<%= will_paginate @theatres %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
      <% @theatres.each do |theatre| %>
      <tr>
        <td><%= theatre.name %></td>
        <td><%= theatre.description %></td>
        <td><%= link_to 'Show', theatre %></td>
        <td><%= link_to 'Edit', edit_theatre_path(theatre) %></td>
        <td><%= link_to 'Destroy', theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theatre', new_theatre_path %>

app/views/theatres/new.html.erb
<h1>New Theatre</h1>

<%= render 'form' %>

<%= link_to 'Back', theatres_path %>

app/views/theatres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theatre.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @theatre.description %>
</p>

<%= link_to 'Edit', edit_theatre_path(@theatre) %> |
<%= link_to 'Back', theatres_path %>